version: '2'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gateway
      MYSQL_USER: prod
      MYSQL_PASSWORD: prod
    ports:
      - 3306:3306
  java:
    build: .
    restart: always
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gateway?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        SPRING_DATASOURCE_USERNAME: prod
        SPRING_DATASOURCE_PASSWORD: prod
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db